---
- name: BGP configuration on ops switches
  hosts: ops
  gather_facts: no
  vars:
    ops_debug: no
  roles:
    - role: bgp

- name: check the switch configuration
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: yes
  tasks:
    - include: tasks/cli/check_running_config.yaml

- name: wait for BGP peering up
  hosts: switches
  gather_facts: no
  tasks:
    - pause: seconds=60

- name: check the BGP peering
  hosts: switches
  gather_facts: no
  vars:
    ops_debug: no
  tasks:
    - name: show ip bgp neighbors
      ops_command:
        commands:
          - show ip bgp neighbors
        provider: "{{ ops_provider }}"
        waitfor:
          - "result[0] contains 'state: Established'"
        interval: 3
        retries: 3
      register: result
      connection: local
    - name: print out the result
      debug: var=result

- name: check the IP routing table (RIB)
  hosts: switches
  gather_facts: yes
  vars:
    ops_debug: no
  tasks:
    - name: show ip route
      ops_command:
        commands:
          - show ip bgp
        provider: "{{ ops_provider }}"
        waitfor:
          - "result[0] contains '30.0.0.0/8'"
          - "result[0] contains '40.0.0.0/8'"
        interval: 3
        retries: 3
      register: result
      connection: local
    - name: print out the result
      debug: var=result
